name = "raportcontabil"
main = "index.js"
compatibility_date = "2024-09-23"

# Dupa ce rulezi:
#   wrangler d1 create balanta_istoric_db
# copiaza "database_id" primit in raspuns aici mai jos.
[[d1_databases]]
binding = "DB"
database_name = "balanta_istoric_db"
database_id = "ab5afe07-c1e5-40d4-bad1-a5ef03c282f1"
